from setuptools import setup, find_packages

setup(
    name='newsagency-classification',
    version='1.0.0',
    author='Lea Marxen',
    author_email='your@email.com',
    description='News Agency Recognition',
    long_description='News Agency Recognition',
    long_description_content_type='text/markdown',
    url='https://github.com/impresso/newsagency-classification',
    packages=find_packages(),
    install_requires=[
        'dependency1',
        'dependency2>=1.0.0',
        'apex==0.9.10dev',
        'dask==2023.10.0',
        'datasets==2.13.1',
        'dkpro_cassis==0.7.5',
        'docopt==0.6.2',
        'ipdb==0.13.13',
        'numpy==1.24.0',
        'nltk==3.7',
        'pandas==1.5.3',
        'pycaprio==0.2.1',
        'pysbd==0.3.4',
        'PyYAML==6.0',
        'requests==2.31.0',
        'scikit_learn==1.2.2',
        'seqeval==1.2.2',
        'setuptools==67.8.0',
        'smart_open==6.3.0',
        'StringDist==1.0.9',
        'tensorboardX==2.6.1',
        'torch==1.13.1',
        'tqdm==4.65.0',
        'transformers==4.36.0',
        'ts==0.5.1',
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)
